CREATE TABLE TY_DEVICE_PROCESS_LOG_20142
(
  PROCESS_ID   NUMBER(15) NOT NULL,
  IMEI         VARCHAR2(50),
  UA           VARCHAR2(100),
  MODEL_NAME  VARCHAR2(100),
  CHANNEL_ID   VARCHAR2(100),
  DEVICE_CODE  VARCHAR2(100),
  GROUP_ID     NUMBER(15),
  BATCH_CODE   VARCHAR2(100),
  PROCESS_TIME VARCHAR2(100),
  CREATE_TIME  DATE DEFAULT SYSDATE NOT NULL
);
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.PROCESS_ID
  IS '唯一主键';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.IMEI
  IS '手机IMEI码';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.UA
  IS '手机UA';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.MODEL_NAME
  IS '机型名称';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.CHANNEL_ID
  IS '渠道ID';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.DEVICE_CODE
  IS '设备编码';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.GROUP_ID
  IS '渠道组ID';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.BATCH_CODE
  IS '批次号';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.PROCESS_TIME
  IS '加工时间';
COMMENT ON COLUMN TY_DEVICE_PROCESS_LOG_20142.CREATE_TIME
  IS '上传时间';


ALTER TABLE TY_DEVICE_PROCESS_LOG_20142
  ADD CONSTRAINT PK_TY_DEVICE_PROCESS_LOG_20142 PRIMARY KEY (PROCESS_ID)
  USING INDEX ;
CREATE INDEX  IDX_DEVICE_LOG_20142_IMEI ON TY_DEVICE_PROCESS_LOG_20142(IMEI);
CREATE INDEX  IDX_DEVICE_LOG_20142_CTIME ON TY_DEVICE_PROCESS_LOG_20142(CREATE_TIME);



  -- CREATE TABLE
CREATE TABLE TY_COUNTER_UPLOAD_LOG_20142
(
  COUNTER_ID   NUMBER(15) NOT NULL,
  IMEI          VARCHAR2(50),
  UA            VARCHAR2(100),
  MODEL_NAME   VARCHAR2(100),
  CHANNEL_ID   VARCHAR2(100),
  DEVICE_CODE  VARCHAR2(100),
  GROUP_ID     NUMBER(15),
  BATCH_CODE   VARCHAR2(100),
  PROCESS_TIME VARCHAR2(100),
  CREATE_TIME  DATE DEFAULT SYSDATE NOT NULL,
  ACTIVE        VARCHAR2(100) NOT NULL
)
;
-- ADD COMMENTS TO THE COLUMNS
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.COUNTER_ID
  IS '唯一主键';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.IMEI
  IS '手机IMEI码';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.UA
  IS '手机UA';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.MODEL_NAME
  IS '机型名称';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.CHANNEL_ID
  IS '渠道ID';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.DEVICE_CODE
  IS '设备编码';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.GROUP_ID
  IS '渠道组ID';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.BATCH_CODE
  IS '批次号';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.PROCESS_TIME
  IS '加工日期';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.CREATE_TIME
  IS '上传时间';
COMMENT ON COLUMN TY_COUNTER_UPLOAD_LOG_20142.ACTIVE
  IS '1：有效到达，2：无效-替换，3：无效-卸载';


ALTER TABLE TY_COUNTER_UPLOAD_LOG_20142 ADD CONSTRAINT PK_TY_COUNTER_UPLOAD_LOG_20142 PRIMARY KEY (COUNTER_ID);
CREATE INDEX  IDX_COUNTER_LOG_20142_IMEI ON TY_COUNTER_UPLOAD_LOG_20142(IMEI);
CREATE INDEX  IDX_COUNTER_LOG_20142_CTIME ON TY_COUNTER_UPLOAD_LOG_20142(CREATE_TIME);



-- CREATE TABLE
CREATE TABLE TY_DICT_INFO
(
  DICT_ID     NUMBER(15) NOT NULL,
  KEY_CODE    VARCHAR2(50) NOT NULL,
  KEY_VALUE   VARCHAR2(50) NOT NULL,
  REMARK      VARCHAR2(1000),
  CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
  UPDATE_TIME DATE DEFAULT SYSDATE NOT NULL
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS
ALTER TABLE TY_DICT_INFO
  ADD CONSTRAINT PK_TY_DICT_INFO PRIMARY KEY (DICT_ID);
ALTER TABLE TY_DICT_INFO
  ADD CONSTRAINT UNIQ_TY_DICT_INFO_KEYCODE UNIQUE (KEY_CODE);



CREATE TABLE TY_COUNTER_FAIL_LOG
(
  FAIL_ID      NUMBER(15) NOT NULL,
  IMEI          VARCHAR2(50),
  UA            VARCHAR2(100),
  MODEL_NAME   VARCHAR2(100),
  CHANNEL_ID   VARCHAR2(100),
  DEVICE_CODE  VARCHAR2(100),
  GROUP_ID     NUMBER(15),
  BATCH_CODE   VARCHAR2(100),
  PROCESS_TIME VARCHAR2(100),
  CREATE_TIME  DATE DEFAULT SYSDATE NOT NULL,
  ACTIVE        VARCHAR2(100) NOT NULL
);
-- ADD COMMENTS TO THE COLUMNS
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.FAIL_ID
  IS '唯一主键';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.IMEI
  IS '手机IMEI码';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.UA
  IS '手机UA';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.MODEL_NAME
  IS '机型名称';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.CHANNEL_ID
  IS '渠道ID';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.DEVICE_CODE
  IS '设备编码';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.GROUP_ID
  IS '渠道组ID';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.BATCH_CODE
  IS '批次号';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.PROCESS_TIME
  IS '加工日期';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.CREATE_TIME
  IS '上传时间';
COMMENT ON COLUMN TY_COUNTER_FAIL_LOG.ACTIVE
  IS '1：有效到达，2：无效-替换，3：无效-卸载';


ALTER TABLE TY_COUNTER_FAIL_LOG
  ADD CONSTRAINT TY_COUNTER_FAIL_LOG PRIMARY KEY (FAIL_ID);
ALTER TABLE TY_COUNTER_FAIL_LOG
  ADD CONSTRAINT UNIQ_COUNTER_FAIL_LOG_IMEI UNIQUE (IMEI);
CREATE INDEX  IDX_TY_FAIL_LOG_CTIME ON TY_COUNTER_FAIL_LOG(CREATE_TIME);


-- CREATE TABLE
CREATE TABLE TY_CHANNEL_VERSION
(
  VERSION_ID  NUMBER(15) NOT NULL,
  CHANNEL_ID  NUMBER(15) NOT NULL,
  MD5VALUE    VARCHAR2(50) NOT NULL,
  PATH        VARCHAR2(500) NOT NULL,
  VERSION     VARCHAR2(50) NOT NULL,
  CREATE_TIME DATE NOT NULL,
  UPDATE_TIME DATE NOT NULL
)
COMMENT ON TABLE TY_CHANNEL_VERSION  IS '渠道对应APK版本库信息';

ALTER TABLE TY_CHANNEL_VERSION ADD CONSTRAINT PK_TY_CHANNEL_VERSION PRIMARY KEY (VERSION_ID);
ALTER TABLE TY_CHANNEL_VERSION ADD CONSTRAINT UNIQ_TY_CHANNEL_VERSION_CID UNIQUE (CHANNEL_ID);



CREATE TABLE TY_APK_INFO  (
   APK_ID         			NUMBER(15)           NOT NULL,
   APK_NAME            VARCHAR2(50)					NOT NULL,
   SOFT_NAME           VARCHAR2(100)					NOT NULL,
   FTP_PATH        		VARCHAR2(500)         NOT NULL,
   MD5VALUE        		VARCHAR2(500)         NOT NULL,
   DOWNLOAD_URL       VARCHAR2(500)         NOT NULL,
   ACTIVE              VARCHAR2(2)           NOT NULL,
   CREATE_TIME        		DATE               DEFAULT SYSDATE NOT NULL,
   UPDATE_TIME        		DATE               DEFAULT SYSDATE NOT NULL
);
ALTER TABLE TY_APK_INFO ADD CONSTRAINT PK_TY_APK_INFO PRIMARY KEY (APK_ID);
COMMENT ON COLUMN TY_APK_INFO.ACTIVE IS 'Y:有效，N:无效';



CREATE TABLE TY_PACKAGE_INFO  (
   PACKAGE_ID         			NUMBER(15)           NOT NULL,
   PACKAGE_NAME            VARCHAR2(100)					NOT NULL,
   GROUP_ID                NUMBER(15),
   BATCH_ID                NUMBER(15)         NOT NULL,
   BATCH_CODE              VARCHAR2(100)         NOT NULL,
   TYPE                    VARCHAR2(2)           NOT NULL,
   ACTIVE                  VARCHAR2(2)           NOT NULL,
   REMARK                  VARCHAR2(1000),
   CREATE_TIME        		DATE               DEFAULT SYSDATE NOT NULL,
   UPDATE_TIME        		DATE               DEFAULT SYSDATE NOT NULL
);
ALTER TABLE TY_PACKAGE_INFO ADD CONSTRAINT PK_TY_PACKAGE_INFO PRIMARY KEY (PACKAGE_ID);
COMMENT ON COLUMN TY_PACKAGE_INFO.ACTIVE IS 'Y:有效，N:无效';
COMMENT ON COLUMN TY_PACKAGE_INFO.TYPE IS 'Y:通用包，N:普通包';

CREATE TABLE TY_PACKAGE_APK_REF  (
   ID         			        NUMBER(15)           NOT NULL,
   PACKAGE_ID         			NUMBER(15)           NOT NULL,
   APK_ID         			    NUMBER(15)           NOT NULL,
   APK_NAME                VARCHAR2(100)					NOT NULL,
   AUTO_RUN                VARCHAR2(2)         NOT NULL,
   DESKTOP_ICON           VARCHAR2(2)         NOT NULL,
   SORT                    NUMBER(10)         NOT NULL,
   ACTIVE                  VARCHAR2(2)         NOT NULL,
   CREATE_TIME        		DATE               DEFAULT SYSDATE NOT NULL
);
ALTER TABLE TY_PACKAGE_APK_REF ADD CONSTRAINT PK_TY_PACKAGE_APK_REF PRIMARY KEY (ID);
COMMENT ON COLUMN TY_PACKAGE_APK_REF.ACTIVE IS 'Y:有效，N:无效';


CREATE TABLE TY_PUBLISH_TASK  (
   PUBLISH_ID         			NUMBER(15)           NOT NULL,
   PACKAGE_NAME            VARCHAR2(100)					NOT NULL,
   PACKAGE_ID              NUMBER(15)         NOT NULL,
   EFFECT_TIME             DATE,
   ACTIVE              VARCHAR2(2)           NOT NULL,
   CREATE_TIME        		DATE               DEFAULT SYSDATE NOT NULL,
   UPDATE_TIME        		DATE               DEFAULT SYSDATE NOT NULL
);
ALTER TABLE TY_PUBLISH_TASK ADD CONSTRAINT PK_TY_PUBLISH_TASK PRIMARY KEY (PUBLISH_ID);
COMMENT ON COLUMN TY_PUBLISH_TASK.ACTIVE IS 'Y:有效，N:无效';


CREATE TABLE TY_PUBLISH_CHANNEL_REF  (
   ID         			      NUMBER(15)           NOT NULL,
   PUBLISH_ID         	  NUMBER(15)           NOT NULL,
   PACKAGE_ID         		NUMBER(15)           NOT NULL,
   GROUP_ID         			NUMBER(15)           NOT NULL,
   CHANNEL_ID         		NUMBER(15)           NOT NULL,
   CREATE_TIME        		DATE                 DEFAULT SYSDATE NOT NULL,
);
ALTER TABLE TY_PUBLISH_CHANNEL_REF ADD CONSTRAINT PK_TY_PUBLISH_CHANNEL_REF PRIMARY KEY (ID);
COMMENT ON COLUMN TY_PUBLISH_CHANNEL_REF.ACTIVE IS 'Y:有效，N:无效';


CREATE TABLE TY_PUBLISH_MODEL_REF  (
   ID         			      NUMBER(15)           NOT NULL,
   PUBLISH_ID         	  NUMBER(15)           NOT NULL,
   PACKAGE_ID         		NUMBER(15)           NOT NULL,
   MODEL_ID         			NUMBER(15)           NOT NULL,
   CREATE_TIME        		DATE                 DEFAULT SYSDATE NOT NULL,
);
ALTER TABLE TY_PUBLISH_MODEL_REF ADD CONSTRAINT PK_TY_PUBLISH_MODEL_REF PRIMARY KEY (ID);
COMMENT ON COLUMN TY_PUBLISH_MODEL_REF.ACTIVE IS 'Y:有效，N:无效';



