
CREATE TABLE "TY_CHANNEL_GROUP" 
(
   "GROUP_ID"           NUMBER(15)           NOT NULL,
   "GROUP_NAME"         VARCHAR2(200)        NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_TY_CHANNEL_GROUP PRIMARY KEY ("GROUP_ID")
);

COMMENT ON TABLE "TY_CHANNEL_GROUP" IS
'渠道组';

COMMENT ON COLUMN "TY_CHANNEL_GROUP"."GROUP_ID" IS
'GROUP_ID';

COMMENT ON COLUMN "TY_CHANNEL_GROUP"."GROUP_NAME" IS
'渠道名称';

COMMENT ON COLUMN "TY_CHANNEL_GROUP"."CREATE_TIME" IS
'创建时间';


CREATE TABLE "TY_CHANNEL_INFO" 
(
   "CHANNEL_ID"         NUMBER(15)           NOT NULL,
   "PARENT_ID"          NUMBER(15)           NOT NULL,
   "GROUP_ID"           NUMBER(15)           NOT NULL,
   "MNG_ID"             NUMBER(15),
   "USER_ID"            NUMBER(15),
   "CHANNEL_NAME"       VARCHAR2(200)        NOT NULL,
   "DESC"               VARCHAR2(2000),
   "LEAF"               VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
   "TYPE"               VARCHAR2(1)          DEFAULT 'O' NOT NULL,
   "LAOWU_ID"           NUMBER(15),
   "QUERY_IMEI_SOURCE"  VARCHAR2(1)          DEFAULT 'Y',
   "ACTIVE"             VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "UPDATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_TY_CHANNEL_INFO PRIMARY KEY ("CHANNEL_ID")
);

COMMENT ON TABLE "TY_CHANNEL_INFO" IS
'渠道信息';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."CHANNEL_ID" IS
'CHANNEL_ID';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."PARENT_ID" IS
'父ID';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."GROUP_ID" IS
'渠道组ID';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."MNG_ID" IS
'负责人ID';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."USER_ID" IS
'用户ID';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."CHANNEL_NAME" IS
'渠道名称';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."DESC" IS
'渠道描述';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."LEAF" IS
'是否叶子节点（Y:叶子节点，N:非叶子节点）';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."TYPE" IS
'渠道类型（L:劳务公司，M:主渠道，C:子渠道，O:其他）';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."LAOWU_ID" IS
'劳务公司ID';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."QUERY_IMEI_SOURCE" IS
'是否可以查询IMEI（Y:可以，N:不可以）';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."ACTIVE" IS
'活动状态（Y:有效，D:删除）';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."CREATE_TIME" IS
'创建时间';

COMMENT ON COLUMN "TY_CHANNEL_INFO"."UPDATE_TIME" IS
'修改时间';


CREATE TABLE "TY_MODEL_INFO" 
(
   "MODEL_ID"           NUMBER(15)           NOT NULL,
   "UA"                 VARCHAR2(100)        NOT NULL,
   "MODEL_NAME"         VARCHAR2(200)        NOT NULL,
   "GROUP_ID"           NUMBER(15)           NOT NULL,
   "TAGNUM"             NUMBER(15)            NOT NULL,
   "TAGPRICE"           NUMBER(15,3)          NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "UPDATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "ACTIVE"             VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
   CONSTRAINT PK_TY_MODEL_INFO PRIMARY KEY ("MODEL_ID")
);

COMMENT ON TABLE "TY_MODEL_INFO" IS
'机型';

COMMENT ON COLUMN "TY_MODEL_INFO"."MODEL_ID" IS
'机型ID';

COMMENT ON COLUMN "TY_MODEL_INFO"."UA" IS
'UA';

COMMENT ON COLUMN "TY_MODEL_INFO"."MODEL_NAME" IS
'机型名称';

COMMENT ON COLUMN "TY_MODEL_INFO"."GROUP_ID" IS
'渠道组ID';

COMMENT ON COLUMN "TY_MODEL_INFO"."TAGNUM" IS
'标签数量';

COMMENT ON COLUMN "TY_MODEL_INFO"."TAGPRICE" IS
'标签单价';

COMMENT ON COLUMN "TY_MODEL_INFO"."CREATE_TIME" IS
'创建时间';

COMMENT ON COLUMN "TY_MODEL_INFO"."UPDATE_TIME" IS
'修改时间';

COMMENT ON COLUMN "TY_MODEL_INFO"."ACTIVE" IS
'活动状态（Y:有效，D:删除）';

alter table "TY_MODEL_INFO" add constraint UNIQ_TY_MODEL_GID_UA unique ("GROUP_ID","UA");

CREATE TABLE "TY_MODEL_CHANNEL_REF" 
(
   "MODEL_ID"           NUMBER(15)           NOT NULL,
   "CHANNEL_ID"         NUMBER(15)           NOT NULL,
   "GROUP_ID"           NUMBER(15)           NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_TY_MODEL_CHANNEL_REF PRIMARY KEY ("MODEL_ID", "CHANNEL_ID")
);

COMMENT ON TABLE "TY_MODEL_CHANNEL_REF" IS
'机型渠道关联表';

COMMENT ON COLUMN "TY_MODEL_CHANNEL_REF"."MODEL_ID" IS
'机型ID';

COMMENT ON COLUMN "TY_MODEL_CHANNEL_REF"."CHANNEL_ID" IS
'渠道ID';

COMMENT ON COLUMN "TY_MODEL_CHANNEL_REF"."GROUP_ID" IS
'渠道组ID';

COMMENT ON COLUMN "TY_MODEL_CHANNEL_REF"."CREATE_TIME" IS
'创建时间';


CREATE TABLE "TY_DEVICE_INFO" 
(
   "DEVICE_ID"          NUMBER(15)           NOT NULL,
   "DEVICE_CODE"        VARCHAR2(50)         NOT NULL,
   "GROUP_ID"           NUMBER(15)           NOT NULL,
   "CHANNEL_ID"         NUMBER(15)           NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "UPDATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "ACTIVE"             VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
   CONSTRAINT PK_TY_DEVICE_INFO PRIMARY KEY ("DEVICE_ID")
);

COMMENT ON TABLE "TY_DEVICE_INFO" IS
'设备信息';

COMMENT ON COLUMN "TY_DEVICE_INFO"."DEVICE_ID" IS
'设备ID';

COMMENT ON COLUMN "TY_DEVICE_INFO"."DEVICE_CODE" IS
'设备编码';

COMMENT ON COLUMN "TY_DEVICE_INFO"."GROUP_ID" IS
'渠道组ID';

COMMENT ON COLUMN "TY_DEVICE_INFO"."CHANNEL_ID" IS
'渠道ID';

COMMENT ON COLUMN "TY_DEVICE_INFO"."CREATE_TIME" IS
'创建时间';

COMMENT ON COLUMN "TY_DEVICE_INFO"."UPDATE_TIME" IS
'修改时间';

COMMENT ON COLUMN "TY_DEVICE_INFO"."ACTIVE" IS
'活动状态（Y:有效，D:删除）';


CREATE TABLE "TY_PARTNER_INFO" 
(
   "PARTNER_ID"         NUMBER(15)           NOT NULL,
   "USER_ID"            NUMBER(15),
   "PARTNER_NAME"       VARCHAR2(50)         NOT NULL,
   "QUERY_IMEI_SOURCE"  VARCHAR2(1)          DEFAULT 'N' NOT NULL,
   "EXPORT_IMEI_SOURCE" VARCHAR2(1)          DEFAULT 'N' NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "UPDATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "ACTIVE"             VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
   CONSTRAINT PK_TY_PARTNER_INFO PRIMARY KEY ("PARTNER_ID")
);

COMMENT ON TABLE "TY_PARTNER_INFO" IS
'合作方信息';

COMMENT ON COLUMN "TY_PARTNER_INFO"."PARTNER_ID" IS
'合作方ID';

COMMENT ON COLUMN "TY_PARTNER_INFO"."USER_ID" IS
'用户ID';

COMMENT ON COLUMN "TY_PARTNER_INFO"."PARTNER_NAME" IS
'合作方名称';

COMMENT ON COLUMN "TY_PARTNER_INFO"."QUERY_IMEI_SOURCE" IS
'是否可以查询IMEI（Y:可以，N:不可以）';

COMMENT ON COLUMN "TY_PARTNER_INFO"."EXPORT_IMEI_SOURCE" IS
'是否可以导出IMEI（Y:可以，N:不可以）';

COMMENT ON COLUMN "TY_PARTNER_INFO"."CREATE_TIME" IS
'创建时间';

COMMENT ON COLUMN "TY_PARTNER_INFO"."UPDATE_TIME" IS
'修改时间';

COMMENT ON COLUMN "TY_PARTNER_INFO"."ACTIVE" IS
'活动状态（Y:有效，D:删除）';



CREATE TABLE "TY_PRODUCT_INFO" 
(
   "PRODUCT_ID"         NUMBER(15)           NOT NULL,
   "PRODUCT_NAME"       VARCHAR2(50)         NOT NULL,
   "PARTNER_ID"         NUMBER(15)           NOT NULL,
   "QUERY_DATA_SOURCE"  VARCHAR2(1)          DEFAULT 'N' NOT NULL,
   "QUERY_START_TIME"   DATE                 DEFAULT SYSDATE NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "UPDATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "ACTIVE"             VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
   CONSTRAINT PK_TY_PRODUCT_INFO PRIMARY KEY ("PRODUCT_ID")
);

COMMENT ON TABLE "TY_PRODUCT_INFO" IS
'产品信息';

COMMENT ON COLUMN "TY_PRODUCT_INFO"."PRODUCT_ID" IS
'产品ID';

COMMENT ON COLUMN "TY_PRODUCT_INFO"."PRODUCT_NAME" IS
'产品名称';

COMMENT ON COLUMN "TY_PRODUCT_INFO"."PARTNER_ID" IS
'合作方ID';

COMMENT ON COLUMN "TY_PRODUCT_INFO"."QUERY_DATA_SOURCE" IS
'是否可以查询（Y:可以，N:不可以）';

COMMENT ON COLUMN "TY_PRODUCT_INFO"."QUERY_START_TIME" IS
'查询开始时间';

COMMENT ON COLUMN "TY_PRODUCT_INFO"."CREATE_TIME" IS
'创建时间';

COMMENT ON COLUMN "TY_PRODUCT_INFO"."UPDATE_TIME" IS
'修改时间';

COMMENT ON COLUMN "TY_PRODUCT_INFO"."ACTIVE" IS
'活动状态（Y:有效，D:删除）';



CREATE TABLE "TY_BATCH_INFO" 
(
   "BATCH_ID"           NUMBER(15)           NOT NULL,
   "BATCH_CODE"         VARCHAR2(50)         NOT NULL,
   "GROUP_ID"           NUMBER(15)           NOT NULL,
   "BATCH_PRODUCT_NAME"  VARCHAR2(2000),
   "BATCH_PRODUCT_NUM"   NUMBER(15),
   "START_TIME"         DATE                 DEFAULT SYSDATE NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "UPDATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "ACTIVE"             VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
   CONSTRAINT PK_TY_BATCH_INFO PRIMARY KEY ("BATCH_ID")
);

COMMENT ON TABLE "TY_BATCH_INFO" IS
'批次信息';

COMMENT ON COLUMN "TY_BATCH_INFO"."BATCH_ID" IS
'批次ID';

COMMENT ON COLUMN "TY_BATCH_INFO"."BATCH_CODE" IS
'批次号';

COMMENT ON COLUMN "TY_BATCH_INFO"."GROUP_ID" IS
'渠道组ID';

COMMENT ON COLUMN "TY_BATCH_INFO"."BATCH_PRODUCT_NAME" IS
'批次关联产品名称';

COMMENT ON COLUMN "TY_BATCH_INFO"."BATCH_PRODUCT_NUM" IS
'批次关联产品数量';

COMMENT ON COLUMN "TY_BATCH_INFO"."START_TIME" IS
'开始时间';

COMMENT ON COLUMN "TY_BATCH_INFO"."CREATE_TIME" IS
'创建时间';

COMMENT ON COLUMN "TY_BATCH_INFO"."UPDATE_TIME" IS
'修改时间';

COMMENT ON COLUMN "TY_BATCH_INFO"."ACTIVE" IS
'活动状态（Y:有效，D:删除）';




CREATE TABLE "TY_BATCH_PRODUCT_REF" 
(
   "BATCH_ID"           NUMBER(15)           NOT NULL,
   "PRODUCT_ID"         NUMBER(15)           NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_TY_BATCH_PRODUCT_REF PRIMARY KEY ("BATCH_ID", "PRODUCT_ID")
);

COMMENT ON TABLE "TY_BATCH_PRODUCT_REF" IS
'批次产品关联表';

COMMENT ON COLUMN "TY_BATCH_PRODUCT_REF"."BATCH_ID" IS
'批次ID';

COMMENT ON COLUMN "TY_BATCH_PRODUCT_REF"."PRODUCT_ID" IS
'产品ID';

COMMENT ON COLUMN "TY_BATCH_PRODUCT_REF"."CREATE_TIME" IS
'创建时间';



CREATE TABLE "TY_DEVICE_SYSTEM" 
(
   "SYSTEM_ID"          NUMBER(15)           NOT NULL,
   "VERSION"            VARCHAR2(50)         NOT NULL,
   "FTP_PATH"           VARCHAR2(500)        NOT NULL,
   "EFFECTIVE_TIME"     DATE                 DEFAULT SYSDATE NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_TY_DEVICE_SYSTEM PRIMARY KEY ("SYSTEM_ID")
);

COMMENT ON TABLE "TY_DEVICE_SYSTEM" IS
'设备系统';

COMMENT ON COLUMN "TY_DEVICE_SYSTEM"."SYSTEM_ID" IS
'设备系统ID';

COMMENT ON COLUMN "TY_DEVICE_SYSTEM"."VERSION" IS
'版本号';

COMMENT ON COLUMN "TY_DEVICE_SYSTEM"."FTP_PATH" IS
'FTP路径';

COMMENT ON COLUMN "TY_DEVICE_SYSTEM"."EFFECTIVE_TIME" IS
'生效时间';

COMMENT ON COLUMN "TY_DEVICE_SYSTEM"."CREATE_TIME" IS
'创建时间';
