CREATE SEQUENCE "SEQ_CHANNEL_GROUP" MINVALUE 5 MAXVALUE 9999999 START WITH 5 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE "SEQ_CHANNEL_INFO";
CREATE SEQUENCE "SEQ_BATCH_INFO";
CREATE SEQUENCE "SEQ_DEVICE_INFO";
CREATE SEQUENCE "SEQ_DEVICE_SYSTEM";
CREATE SEQUENCE "SEQ_MODEL_INFO";
CREATE SEQUENCE "SEQ_PARTNER_INFO";
CREATE SEQUENCE "SEQ_PRODUCT_INFO";

CREATE SEQUENCE "SEQ_BATCH_INFO_TY";
CREATE SEQUENCE "SEQ_BATCH_INFO_DB";
CREATE SEQUENCE "SEQ_BATCH_INFO_QT";