INSERT INTO TY_CHANNEL_GROUP(GROUP_ID,GROUP_NAME) VALUES(1,'天音渠道');
INSERT INTO TY_CHANNEL_GROUP(GROUP_ID,GROUP_NAME) VALUES(2,'地包渠道');
INSERT INTO TY_CHANNEL_GROUP(GROUP_ID,GROUP_NAME) VALUES(3,'其他渠道');
INSERT INTO TY_CHANNEL_GROUP(GROUP_ID,GROUP_NAME) VALUES(4,'劳务渠道');