CREATE TABLE "TY_APK_INFO"
(
   "APK_ID"             NUMBER(15)           NOT NULL,
   "PRODUCT_NAME"      VARCHAR2(200)        NOT NULL,
   "APK_NAME"           VARCHAR2(200),
   "FTP_PATH"           VARCHAR2(200),
   "ACTIVE"             VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
   "CREATE_TIME"        DATE                 DEFAULT SYSDATE NOT NULL,
   "UPDATE_TIME"        DATE,
   CONSTRAINT PK_TY_APK_INFO PRIMARY KEY ("APK_ID")
);

COMMENT ON TABLE "TY_APK_INFO" IS
'APK管理';

COMMENT ON COLUMN "TY_APK_INFO"."APK_ID" IS
'APK_ID';

COMMENT ON COLUMN "TY_APK_INFO"."PRODUCT_NAME" IS
'产品名称';

COMMENT ON COLUMN "TY_APK_INFO"."APK_NAME" IS
'APK名称';

COMMENT ON COLUMN "TY_APK_INFO"."FTP_PATH" IS
'ftp路径';

COMMENT ON COLUMN "TY_APK_INFO"."ACTIVE" IS
'活动状态（Y:有效，D:删除）';

COMMENT ON COLUMN "TY_APK_INFO"."CREATE_TIME" IS
'创建时间';