
CREATE TABLE TY_RESOURCE
(
  RESOURCE_ID NUMBER(15) NOT NULL,
  PARENT_ID   NUMBER(15),
  RES_NAME    VARCHAR2(50) NOT NULL,
  CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
  RES_URL     VARCHAR2(60),
  FULL_PATH   VARCHAR2(60),
  LEVELS      NUMBER(20)
);
ALTER TABLE TY_RESOURCE  ADD PRIMARY KEY (RESOURCE_ID);








CREATE TABLE TY_ROLE
(
  ROLE_ID          NUMBER(15) NOT NULL,
  ROLE_NAME   VARCHAR2(20) NOT NULL,
  PARENT_ID   NUMBER(15),  
  FULL_PATH   VARCHAR2(100),
  LEVELS      NUMBER(11) NOT NULL,
  CREATE_TIME DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE TY_ROLE ADD PRIMARY KEY (ROLE_ID);







CREATE TABLE TY_ROLE_RESOURCE_REF
(
  ID          NUMBER(15) NOT NULL,
  ROLE_ID     NUMBER(15),
  RESOURCE_ID      NUMBER(15),
  ACCES       NUMBER(2),
  CREATE_TIME DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE TY_ROLE_RESOURCE_REF ADD PRIMARY KEY (ID);








CREATE TABLE TY_USER
(
  USER_ID          NUMBER(15) NOT NULL,
  LOGIN_NAME    VARCHAR2(50) NOT NULL,
  REAL_NAME    VARCHAR2(50) NOT NULL,
  PASSWORD    VARCHAR2(128) NOT NULL,
  CELLPHONE   VARCHAR2(18) ,
  ADDRESS     VARCHAR2(256) ,
  STATUS      NUMBER(2) NOT NULL,
  TYPE        NUMBER(2) DEFAULT 1 NOT NULL,
  CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
  UPDATE_TIME DATE
);
ALTER TABLE TY_USER ADD PRIMARY KEY (USER_ID);
COMMENT ON COLUMN TY_USER.TYPE IS '普通用户-1 负责人-2 管理员用户-3';





CREATE TABLE TY_USER_ROLE_REF
(
  ID          NUMBER(15) NOT NULL,
  USER_ID    NUMBER(15) NOT NULL,
  ROLE_ID     NUMBER(15) NOT NULL,
  CREATE_TIME DATE DEFAULT SYSDATE NOT NULL 
);
ALTER TABLE TY_USER_ROLE_REF ADD PRIMARY KEY (ID);
  

