alter table TY_LOG_ARRIVE_STAT_TEMP rename column TOTAL_NUM to INVALID_NUM;
alter table TY_PRODUCT_ARRIVE_STAT_TEMP rename column TOTAL_NUM to INVALID_NUM;

Insert into TY_RESOURCE (RESOURCE_ID,PARENT_ID,RES_NAME,RES_URL,FULL_PATH,LEVELS,CREATE_TIME) values (	30017	,	300	,'其他渠道安装查询'			,'partnerquery_qt_process'					,'',	2	,	SYSDATE	);
insert into TY_ROLE_RESOURCE_REF (ID, ROLE_ID, RESOURCE_ID, CREATE_TIME) values (SEQ_ROLE_RESOURCE_REF.NEXTVAL, 1, 30017  , SYSDATE);
